# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'Stripe/ApplePay'
pod 'ApplePayStubs'
#target 'ApplePaySwag' do
#
#end
#
#target 'ApplePaySwagTests' do
#
#end
#
